### ISSUE TITLE
Logo Change

### ISSUE THREAD

**Issue by tuxology** [anuradha1992/askbotfedoratest#1]
Please change to logo with this one : https://getfedora.org/static/images/fedora_infinity_140x140.png

The colors in the current logo are not right.

**Comment by anuradha1992** [comment]
The logo is now changed to the one you have given in the above link.

**Comment by tuxology** [comment]
Cool :+1:

**Comment by anuradha1992** [comment]
This issue was moved to fedoradesign/askfedora-redesign#11
