### ISSUE TITLE
More padding between sidebar and questions

### ISSUE THREAD

**Issue by tuxology** [anuradha1992/askbotfedoratest#10]
Things are too close to each other and look slightly crammed I think.

![image](https://cloud.githubusercontent.com/assets/3373857/9431430/18f202ec-49df-11e5-8659-5194d8a254a8.png)

You can probably experiemnt with more padding and spacing to see what suits well. I suggest looking at other webistes for inspiration on sidebars and the idea of isolating data. Even within the sidebar, things are too crammed. In the long run, we should think about it a bit. Possibly seggregating data according to its purpose.

**Comment by anuradha1992** [comment]
I have increased the padding so that it looks like the following now.

![1 4](https://cloud.githubusercontent.com/assets/6246946/9488930/e69e35ea-4bfa-11e5-921d-01d768b8262a.PNG)

**Comment by anuradha1992** [comment]
I have increased the padding so that it looks like the following now.

![1 5](https://cloud.githubusercontent.com/assets/6246946/9488986/54e28218-4bfb-11e5-8e93-22d139621c23.PNG)

**Comment by anuradha1992** [comment]
This issue was moved to fedoradesign/askfedora-redesign#6
