### ISSUE TITLE
Original tag list not populated when closing tag

### ISSUE THREAD

**Issue by tuxology** [anuradha1992/askbotfedoratest#12]
### Current behaviour
1. Go to questions page
2. Click any tag
3. Questions relevant to that tag come.
4. Tag list in side bar gets updates with fewer tags
5. Close tag by clicking 'X' button.
6. Tag list in sidebar remains same as in step 4
### Intended behaviour
1. Go to questions page
2. Click any tag
3. Questions relevant to that tag come.
4. Tag list in side bar gets updates with fewer tags
5. Close tag by clicking 'X' button.
6. Tag list in sidebar gets updates to original state

**Comment by anuradha1992** [comment]
This issue was moved to fedoradesign/askfedora-redesign#8
