### ISSUE TITLE
Popups on icons

### ISSUE THREAD

**Issue by tuxology** [anuradha1992/askbotfedoratest#5]
Need popup hints on the icons as you had decided before in http://askfedoratest-anuradhaw.rhcloud.com/main

![image](https://cloud.githubusercontent.com/assets/3373857/9372269/b741889c-46aa-11e5-9c14-222921affd13.png)

**Comment by anuradha1992** [comment]
I have included the pop up hints so that they appear on top of the font awesome icons when hovered.

**Comment by tuxology** [comment]
Thanks, this works

**Comment by tuxology** [comment]
I realized that they are a bit visually misaligned with the icon. Can we have them like "pop-down" hints? For example, hover over your image on header in Github.

**Comment by anuradha1992** [comment]
This issue was moved to fedoradesign/askfedora-redesign#1
