### ISSUE TITLE
Slight border on "cards"

### ISSUE THREAD

**Issue by tuxology** [anuradha1992/askbotfedoratest#7]
Some slight border on cards would be helpful IMO as the grey is essentialy quite light. For example, look at the mockups you did : 

![image](https://cloud.githubusercontent.com/assets/3373857/9431308/519af908-49dc-11e5-9ca5-bd4ab38ceebc.png)

This would probably apply to "cards" used everywhere such as in Profile view

**Comment by anuradha1992** [comment]
I have added the light border around the question cards as well as around the other cards.

**Comment by anuradha1992** [comment]
This issue was moved to fedoradesign/askfedora-redesign#3
